%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.6.0

-ifndef(katja_pb).
-define(katja_pb, true).

-define(katja_pb_gpb_version, "4.6.0").

-ifndef('RIEMANNPB_STATE_PB_H').
-define('RIEMANNPB_STATE_PB_H', true).
-record(riemannpb_state,
        {time                   :: integer() | undefined, % = 1, 32 bits
         state                  :: iodata() | undefined, % = 2
         service                :: iodata() | undefined, % = 3
         host                   :: iodata() | undefined, % = 4
         description            :: iodata() | undefined, % = 5
         once                   :: boolean() | 0 | 1 | undefined, % = 6
         tags = []              :: [iodata()] | undefined, % = 7
         ttl                    :: float() | integer() | infinity | '-infinity' | nan | undefined % = 8
        }).
-endif.

-ifndef('RIEMANNPB_EVENT_PB_H').
-define('RIEMANNPB_EVENT_PB_H', true).
-record(riemannpb_event,
        {time                   :: integer() | undefined, % = 1, 32 bits
         state                  :: iodata() | undefined, % = 2
         service                :: iodata() | undefined, % = 3
         host                   :: iodata() | undefined, % = 4
         description            :: iodata() | undefined, % = 5
         tags = []              :: [iodata()] | undefined, % = 7
         ttl                    :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 8
         attributes = []        :: [katja_pb:riemannpb_attribute()] | undefined, % = 9
         time_micros            :: integer() | undefined, % = 10, 32 bits
         metric_sint64          :: integer() | undefined, % = 13, 32 bits
         metric_d               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 14
         metric_f               :: float() | integer() | infinity | '-infinity' | nan | undefined % = 15
        }).
-endif.

-ifndef('RIEMANNPB_QUERY_PB_H').
-define('RIEMANNPB_QUERY_PB_H', true).
-record(riemannpb_query,
        {string                 :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('RIEMANNPB_MSG_PB_H').
-define('RIEMANNPB_MSG_PB_H', true).
-record(riemannpb_msg,
        {ok                     :: boolean() | 0 | 1 | undefined, % = 2
         error                  :: iodata() | undefined, % = 3
         states = []            :: [katja_pb:riemannpb_state()] | undefined, % = 4
         query                  :: katja_pb:riemannpb_query() | undefined, % = 5
         events = []            :: [katja_pb:riemannpb_event()] | undefined % = 6
        }).
-endif.

-ifndef('RIEMANNPB_ATTRIBUTE_PB_H').
-define('RIEMANNPB_ATTRIBUTE_PB_H', true).
-record(riemannpb_attribute,
        {key                    :: iodata(),        % = 1
         value                  :: iodata() | undefined % = 2
        }).
-endif.

-endif.
